-- P915 (early draft — superseded by 135-p915-tighten-dispatchable-threshold.sql)
--
-- This file was an earlier draft of the P915 migration.  The view change
-- (10 min → 60 s) was subsequently absorbed into P1132 migrations 171 and 173,
-- which also added presence_state and pg_stat_activity liveness signals.
-- Applying a CREATE OR REPLACE VIEW here would strip those later additions.
--
-- The canonical deliverable for P915 is in 135-p915-tighten-dispatchable-threshold.sql
-- (composite index only).  This file is a no-op to avoid accidental view regression.

-- intentional no-op; see 135-p915-tighten-dispatchable-threshold.sql
