-- P907 AC1: add thread_id column to roadmap.message_ledger
-- Populated by a BEFORE INSERT trigger that walks reply_to to find the root.

-- 1. Add column
ALTER TABLE roadmap.message_ledger 
  ADD COLUMN IF NOT EXISTS thread_id BIGINT NULL;

-- 2. Allow manual ID insertion for the trigger
-- Identity columns 'GENERATED ALWAYS' do not allow setting NEW.id in BEFORE triggers.
-- Switching to 'GENERATED BY DEFAULT' preserves identity semantics while allowing the trigger
-- to pre-fetch the nextval for root messages.
ALTER TABLE roadmap.message_ledger 
  ALTER COLUMN id DROP IDENTITY;
ALTER TABLE roadmap.message_ledger 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 3. Backfill via recursive CTE
WITH RECURSIVE thread_roots AS (
    -- Base case: root messages (already in DB)
    SELECT id, id as root_id
    FROM roadmap.message_ledger
    WHERE reply_to IS NULL
    
    UNION ALL
    
    -- Recursive case: children
    SELECT m.id, tr.root_id
    FROM roadmap.message_ledger m
    JOIN thread_roots tr ON m.reply_to = tr.id
)
UPDATE roadmap.message_ledger m
SET thread_id = tr.root_id
FROM thread_roots tr
WHERE m.id = tr.id AND m.thread_id IS NULL;

-- 4. Set NOT NULL after backfill
-- If there were rows with missing parents (broken threads), they remain NULL.
-- For production safety, we'll set root = id for any remaining orphans.
UPDATE roadmap.message_ledger SET thread_id = id WHERE thread_id IS NULL;

ALTER TABLE roadmap.message_ledger 
  ALTER COLUMN thread_id SET NOT NULL;

-- 5. Index
CREATE INDEX IF NOT EXISTS idx_message_ledger_thread_id_created_at 
    ON roadmap.message_ledger (thread_id, created_at) 
 WHERE thread_id IS NOT NULL;

-- 6. Trigger Function
CREATE OR REPLACE FUNCTION roadmap.fn_message_ledger_set_thread_id()
RETURNS TRIGGER AS $$
DECLARE
    v_root_id BIGINT;
BEGIN
    -- If NEW.thread_id is already set, return early (app pre-computed).
    IF NEW.thread_id IS NOT NULL THEN
        RETURN NEW;
    END IF;

    -- If root message (no reply_to)
    IF NEW.reply_to IS NULL THEN
        -- Assign ID from sequence so we can use it for thread_id
        IF NEW.id IS NULL THEN
            NEW.id := nextval(pg_get_serial_sequence('roadmap.message_ledger', 'id'));
        END IF;
        NEW.thread_id := NEW.id;
    ELSE
        -- Walk recursively up reply_to chain
        -- Optimization: just get parent's thread_id
        SELECT thread_id INTO v_root_id
        FROM roadmap.message_ledger
        WHERE id = NEW.reply_to;
        
        IF v_root_id IS NULL THEN
            -- Parent has no thread_id? (e.g. during backfill or if parent was inserted before trigger)
            -- We should walk up until we find a root.
            WITH RECURSIVE find_root AS (
                SELECT id, reply_to, id as root_id
                FROM roadmap.message_ledger
                WHERE id = NEW.reply_to
                
                UNION ALL
                
                SELECT m.id, m.reply_to, m.id
                FROM roadmap.message_ledger m
                JOIN find_root fr ON m.id = fr.reply_to
            )
            SELECT root_id INTO v_root_id
            FROM find_root
            WHERE reply_to IS NULL
            LIMIT 1;
        END IF;
        
        NEW.thread_id := COALESCE(v_root_id, NEW.reply_to);
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 7. Trigger
DROP TRIGGER IF EXISTS trg_message_ledger_set_thread_id ON roadmap.message_ledger;
CREATE TRIGGER trg_message_ledger_set_thread_id
    BEFORE INSERT ON roadmap.message_ledger
    FOR EACH ROW
    EXECUTE FUNCTION roadmap.fn_message_ledger_set_thread_id();
