-- P674: Extend notification_queue with payload column for kind-based routing.
--
-- The new notification contract: callers write (severity, kind, payload) instead of
-- hardcoding `channel`. The router resolves kind + severity to transport via
-- notification_route. This migration adds the payload column to materialize the
-- caller's data so templates and transports can access it directly.

-- Add payload column if it doesn't exist.
-- (The schema.ts might have created it already in test mode, but the live DB
--  might not have it yet; idempotent with IF NOT EXISTS.)
ALTER TABLE roadmap.notification_queue
  ADD COLUMN IF NOT EXISTS payload jsonb NOT NULL DEFAULT '{}'::jsonb;

-- Ensure the notification_route table exists with proper schema.
-- (schema.ts created it in test/integration runs; live DB created it too.)
CREATE TABLE IF NOT EXISTS roadmap.notification_route (
  id              bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  kind            text NOT NULL,                   -- e.g. 'schema_drift', 'spawn_no_ladder'
  severity_min    text NOT NULL DEFAULT 'INFO',    -- INFO|ALERT|URGENT|CRITICAL
  transport       text NOT NULL,                   -- 'discord_webhook'|'mcp_agent'|'in_app'|'log_only'|'github_issue'|'email'|'sms'
  target          text,                            -- transport-specific (URL, agent identity, channel)
  template        text,                            -- optional Jinja-ish payload template (unused for now)
  enabled         boolean NOT NULL DEFAULT true,
  priority        integer NOT NULL DEFAULT 100,    -- ordering when multiple routes match
  notes           text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT notification_route_severity_min_check
    CHECK (severity_min = ANY (ARRAY['INFO'::text, 'ALERT'::text, 'URGENT'::text, 'CRITICAL'::text])),
  CONSTRAINT notification_route_transport_check
    CHECK (transport = ANY (ARRAY['discord_webhook'::text, 'mcp_agent'::text, 'in_app'::text, 'log_only'::text, 'github_issue'::text, 'email'::text, 'sms'::text]))
);

CREATE INDEX IF NOT EXISTS idx_notification_route_kind
  ON roadmap.notification_route (kind, enabled);

-- Seed default routes for known kinds. These are the routes that make
-- the P674 migration observably backward-compatible: existing callers that
-- wrote kind='spawn_no_ladder' now go to Discord, just like they did before.
--
-- Each INSERT checks first to make this idempotent.
-- Multiple runs of this migration are safe.

INSERT INTO roadmap.notification_route (kind, severity_min, transport, target, priority, notes)
SELECT 'spawn_no_ladder', 'ALERT', 'discord_webhook', NULL, 10, 'P674: spawn escalation failed'
WHERE NOT EXISTS (
  SELECT 1 FROM roadmap.notification_route
  WHERE kind = 'spawn_no_ladder' AND severity_min = 'ALERT' AND transport = 'discord_webhook'
);

INSERT INTO roadmap.notification_route (kind, severity_min, transport, target, priority, notes)
SELECT 'spawn_no_ladder', 'ALERT', 'log_only', NULL, 20, 'P674: always log ALERT-or-higher'
WHERE NOT EXISTS (
  SELECT 1 FROM roadmap.notification_route
  WHERE kind = 'spawn_no_ladder' AND severity_min = 'ALERT' AND transport = 'log_only'
);

INSERT INTO roadmap.notification_route (kind, severity_min, transport, target, priority, notes)
SELECT 'schema_drift', 'INFO', 'discord_webhook', NULL, 10, 'P674: schema drift monitor'
WHERE NOT EXISTS (
  SELECT 1 FROM roadmap.notification_route
  WHERE kind = 'schema_drift' AND severity_min = 'INFO' AND transport = 'discord_webhook'
);

INSERT INTO roadmap.notification_route (kind, severity_min, transport, target, priority, notes)
SELECT 'schema_drift_repeated', 'CRITICAL', 'discord_webhook', NULL, 10, 'P674: repeated schema drift'
WHERE NOT EXISTS (
  SELECT 1 FROM roadmap.notification_route
  WHERE kind = 'schema_drift_repeated' AND severity_min = 'CRITICAL' AND transport = 'discord_webhook'
);

INSERT INTO roadmap.notification_route (kind, severity_min, transport, target, priority, notes)
SELECT 'schema_drift_repeated', 'CRITICAL', 'log_only', NULL, 20, 'P674: always log CRITICAL'
WHERE NOT EXISTS (
  SELECT 1 FROM roadmap.notification_route
  WHERE kind = 'schema_drift_repeated' AND severity_min = 'CRITICAL' AND transport = 'log_only'
);

INSERT INTO roadmap.notification_route (kind, severity_min, transport, target, priority, notes)
SELECT 'notification_dispatch_failed', 'CRITICAL', 'log_only', NULL, 10, 'P674: router itself failed'
WHERE NOT EXISTS (
  SELECT 1 FROM roadmap.notification_route
  WHERE kind = 'notification_dispatch_failed' AND severity_min = 'CRITICAL' AND transport = 'log_only'
);

INSERT INTO roadmap.notification_route (kind, severity_min, transport, target, priority, notes)
SELECT 'spawn_ladder_exhausted', 'CRITICAL', 'discord_webhook', NULL, 10, 'P674: escalation exhausted'
WHERE NOT EXISTS (
  SELECT 1 FROM roadmap.notification_route
  WHERE kind = 'spawn_ladder_exhausted' AND severity_min = 'CRITICAL' AND transport = 'discord_webhook'
);

INSERT INTO roadmap.notification_route (kind, severity_min, transport, target, priority, notes)
SELECT 'spawn_ladder_exhausted', 'CRITICAL', 'log_only', NULL, 20, 'P674: always log CRITICAL'
WHERE NOT EXISTS (
  SELECT 1 FROM roadmap.notification_route
  WHERE kind = 'spawn_ladder_exhausted' AND severity_min = 'CRITICAL' AND transport = 'log_only'
);

INSERT INTO roadmap.notification_route (kind, severity_min, transport, target, priority, notes)
SELECT 'dispatch_loop_detected', 'ALERT', 'discord_webhook', NULL, 10, 'P674: dispatch loop'
WHERE NOT EXISTS (
  SELECT 1 FROM roadmap.notification_route
  WHERE kind = 'dispatch_loop_detected' AND severity_min = 'ALERT' AND transport = 'discord_webhook'
);

INSERT INTO roadmap.notification_route (kind, severity_min, transport, target, priority, notes)
SELECT 'dispatch_loop_detected', 'CRITICAL', 'log_only', NULL, 20, 'P674: always log CRITICAL'
WHERE NOT EXISTS (
  SELECT 1 FROM roadmap.notification_route
  WHERE kind = 'dispatch_loop_detected' AND severity_min = 'CRITICAL' AND transport = 'log_only'
);

INSERT INTO roadmap.notification_route (kind, severity_min, transport, target, priority, notes)
SELECT 'route_throttled', 'ALERT', 'discord_webhook', NULL, 10, 'P674: throttle alert'
WHERE NOT EXISTS (
  SELECT 1 FROM roadmap.notification_route
  WHERE kind = 'route_throttled' AND severity_min = 'ALERT' AND transport = 'discord_webhook'
);

INSERT INTO roadmap.notification_route (kind, severity_min, transport, target, priority, notes)
SELECT 'route_throttled', 'INFO', 'log_only', NULL, 20, 'P674: always log'
WHERE NOT EXISTS (
  SELECT 1 FROM roadmap.notification_route
  WHERE kind = 'route_throttled' AND severity_min = 'INFO' AND transport = 'log_only'
);
