/**
 * Exit code catalog per cli-hive-contract.md §3
 *
 * Maps error codes to POSIX exit codes (0-127, 99 for internal errors).
 * Used by the CLI to communicate errors to callers in a structured way.
 */

export const EXIT_CODES = {
  SUCCESS: 0,
  USAGE: 1,
  NOT_FOUND: 2,
  PERMISSION_DENIED: 3,
  CONFLICT: 4,
  REMOTE_FAILURE: 5,
  INVALID_STATE: 6,
  BUDGET_EXHAUSTED: 7,
  POLICY_DENIED: 8,
  TIMEOUT: 9,
  RATE_LIMITED: 10,
  SCHEMA_DRIFT: 11,
  MCP_UNREACHABLE: 12,
  DB_UNREACHABLE: 13,
  ENCODING_ERROR: 14,
  INTERNAL_ERROR: 99,
} as const;

export type ExitCodeKey = keyof typeof EXIT_CODES;

/**
 * Maps error codes (SCREAMING_SNAKE_CASE) to exit codes.
 *
 * This is the canonical mapping per contract §4.
 */
export const ERROR_CODE_TO_EXIT_CODE: Record<string, number> = {
  // Usage & validation errors
  USAGE: EXIT_CODES.USAGE,
  INVALID_FLAG: EXIT_CODES.USAGE,
  MISSING_ARGUMENT: EXIT_CODES.USAGE,
  MALFORMED_INPUT: EXIT_CODES.USAGE,

  // Not found errors
  NOT_FOUND: EXIT_CODES.NOT_FOUND,
  PROPOSAL_NOT_FOUND: EXIT_CODES.NOT_FOUND,
  AGENCY_NOT_FOUND: EXIT_CODES.NOT_FOUND,
  WORKFLOW_NOT_FOUND: EXIT_CODES.NOT_FOUND,
  PROJECT_NOT_FOUND: EXIT_CODES.NOT_FOUND,
  ROUTE_NOT_FOUND: EXIT_CODES.NOT_FOUND,
  RESOURCE_NOT_FOUND: EXIT_CODES.NOT_FOUND,

  // Permission errors
  PERMISSION_DENIED: EXIT_CODES.PERMISSION_DENIED,
  INSUFFICIENT_ROLE: EXIT_CODES.PERMISSION_DENIED,
  NO_LEASE_OWNER: EXIT_CODES.PERMISSION_DENIED,
  NOT_OP_PRIVILEGE: EXIT_CODES.PERMISSION_DENIED,

  // Conflict errors
  CONFLICT: EXIT_CODES.CONFLICT,
  ALREADY_CLAIMED: EXIT_CODES.CONFLICT,
  ALREADY_LEASED: EXIT_CODES.CONFLICT,
  INVALID_TRANSITION: EXIT_CODES.CONFLICT,
  STATE_CONFLICT: EXIT_CODES.CONFLICT,
  MISSING_YES_FLAG: EXIT_CODES.CONFLICT,
  DESTRUCTIVE_REQUIRES_YES: EXIT_CODES.CONFLICT,

  // Remote failures (transient)
  REMOTE_FAILURE: EXIT_CODES.REMOTE_FAILURE,
  MCP_TIMEOUT: EXIT_CODES.REMOTE_FAILURE,
  DB_CONNECTION_FAILED: EXIT_CODES.REMOTE_FAILURE,
  SERVICE_UNAVAILABLE: EXIT_CODES.REMOTE_FAILURE,

  // State errors
  INVALID_STATE: EXIT_CODES.INVALID_STATE,
  INVALID_PROPOSAL_STATE: EXIT_CODES.INVALID_STATE,
  CANNOT_TRANSITION: EXIT_CODES.INVALID_STATE,

  // Budget errors
  BUDGET_EXHAUSTED: EXIT_CODES.BUDGET_EXHAUSTED,
  PROJECT_BUDGET_EXHAUSTED: EXIT_CODES.BUDGET_EXHAUSTED,
  AGENCY_BUDGET_EXHAUSTED: EXIT_CODES.BUDGET_EXHAUSTED,

  // Policy errors
  POLICY_DENIED: EXIT_CODES.POLICY_DENIED,
  HOST_POLICY_BLOCKED: EXIT_CODES.POLICY_DENIED,
  PROVIDER_POLICY_BLOCKED: EXIT_CODES.POLICY_DENIED,
  CREDENTIAL_INACTIVE: EXIT_CODES.POLICY_DENIED,

  // Timeout errors (transient)
  TIMEOUT: EXIT_CODES.TIMEOUT,
  SCAN_TIMEOUT: EXIT_CODES.TIMEOUT,
  MCP_POLL_TIMEOUT: EXIT_CODES.TIMEOUT,

  // Rate limit errors (transient)
  RATE_LIMITED: EXIT_CODES.RATE_LIMITED,
  API_RATE_LIMIT: EXIT_CODES.RATE_LIMITED,

  // Schema errors
  SCHEMA_DRIFT: EXIT_CODES.SCHEMA_DRIFT,
  SCHEMA_VERSION_INCOMPATIBLE: EXIT_CODES.SCHEMA_DRIFT,

  // MCP unreachable (transient)
  MCP_UNREACHABLE: EXIT_CODES.MCP_UNREACHABLE,

  // DB unreachable (transient)
  DB_UNREACHABLE: EXIT_CODES.DB_UNREACHABLE,

  // Encoding errors
  ENCODING_ERROR: EXIT_CODES.ENCODING_ERROR,
  INVALID_JSON: EXIT_CODES.ENCODING_ERROR,
  INVALID_YAML: EXIT_CODES.ENCODING_ERROR,

  // Internal errors
  INTERNAL_ERROR: EXIT_CODES.INTERNAL_ERROR,
};

/**
 * Convert an error code to an exit code.
 *
 * If the error code is not recognized, defaults to INTERNAL_ERROR (99).
 */
export function mapErrorCodeToExitCode(errorCode: string): number {
  return ERROR_CODE_TO_EXIT_CODE[errorCode] ?? EXIT_CODES.INTERNAL_ERROR;
}

/**
 * Check if an exit code is retriable (transient error).
 */
export function isRetriable(exitCode: number): boolean {
  return (
    exitCode === EXIT_CODES.REMOTE_FAILURE ||
    exitCode === EXIT_CODES.TIMEOUT ||
    exitCode === EXIT_CODES.RATE_LIMITED ||
    exitCode === EXIT_CODES.MCP_UNREACHABLE ||
    exitCode === EXIT_CODES.DB_UNREACHABLE
  );
}
