#!/usr/bin/env -S bun run
/**
 * P499: PgBouncer provisioning script.
 *
 * Reads active project DSNs from roadmap.project, then writes:
 *   /etc/pgbouncer/pgbouncer.ini   — one [databases] stanza per active project
 *   /etc/pgbouncer/userlist.txt    — SCRAM-SHA-256 password hashes (read from ~/.pgpass)
 *
 * Run as root or with sudo.  Called:
 *   - At deploy time (first provision)
 *   - By the tenant_db_provisioned NOTIFY listener (see AC-2 in P499)
 *
 * Usage:
 *   sudo bun scripts/pgbouncer/provision-pgbouncer.ts [--dry-run]
 */

import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { Pool } from "pg";

const DRY_RUN = process.argv.includes("--dry-run");
// --watch: after initial provision, keep running and re-provision on tenant_db_provisioned NOTIFY
const WATCH_MODE = process.argv.includes("--watch");

const PGBOUNCER_INI = "/etc/pgbouncer/pgbouncer.ini";
const USERLIST_TXT = "/etc/pgbouncer/userlist.txt";

const PGHOST = process.env.PGHOST ?? "127.0.0.1";
// Always connect directly to Postgres for provisioning (not through PgBouncer)
const PGPORT_DIRECT = Number(process.env.PGPORT_DIRECT ?? process.env.PGPORT ?? 5432);
const PGUSER = process.env.PGUSER ?? (() => { throw new Error("PGUSER is required"); })();
const PGDATABASE = process.env.PGDATABASE ?? "agenthive";
const PGBOUNCER_PORT = Number(process.env.PGBOUNCER_PORT ?? 6432);

interface ProjectRow {
  slug: string;
  db_host: string | null;
  db_port: number | null;
  db_name: string | null;
  db_user: string | null;
}

async function loadProjects(pool: Pool): Promise<ProjectRow[]> {
  const result = await pool.query<ProjectRow>(`
    SELECT
      slug,
      db_host,
      db_port,
      db_name,
      db_user
    FROM roadmap.project
    WHERE is_active = true
      AND db_name IS NOT NULL
    ORDER BY slug
  `);
  return result.rows;
}

function buildIni(projects: ProjectRow[]): string {
  const lines: string[] = [
    "# Auto-generated by scripts/pgbouncer/provision-pgbouncer.ts (P499)",
    "# DO NOT EDIT MANUALLY — re-run this script to regenerate.",
    "",
    "[databases]",
    `# control-plane database`,
    `${PGDATABASE} = host=${PGHOST} port=${PGPORT_DIRECT} dbname=${PGDATABASE} user=${PGUSER}`,
    `# pgbouncer admin console (internal — not proxied)`,
    `pgbouncer = host=${PGHOST} port=${PGPORT_DIRECT} dbname=pgbouncer`,
  ];

  for (const p of projects) {
    const host = p.db_host ?? PGHOST;
    const port = p.db_port ?? PGPORT_DIRECT;
    const dbname = p.db_name!;
    const user = p.db_user ?? PGUSER;
    lines.push(`${p.slug} = host=${host} port=${port} dbname=${dbname} user=${user}`);
  }

  lines.push(
    "",
    "[pgbouncer]",
    `listen_addr = 127.0.0.1`,
    `listen_port = ${PGBOUNCER_PORT}`,
    `auth_type = scram-sha-256`,
    `auth_file = ${USERLIST_TXT}`,
    `pool_mode = transaction`,
    `max_client_conn = 500`,
    `default_pool_size = 20`,
    `reserve_pool_size = 5`,
    `reserve_pool_timeout = 3`,
    `server_idle_timeout = 600`,
    `client_idle_timeout = 0`,
    `server_lifetime = 3600`,
    `log_connections = 0`,
    `log_disconnections = 0`,
    `log_pooler_errors = 1`,
    `stats_period = 60`,
    `# sd_notify for systemd Type=notify (WatchdogSec=30s)`,
    `service_name = pgbouncer`,
    "",
  );

  return lines.join("\n");
}

function buildUserlist(): string {
  // Read hashed passwords from the system auth_file if available,
  // otherwise instruct the operator to populate manually.
  // PgBouncer userlist.txt format: "username" "md5hash_or_scram_verifier"
  // For SCRAM-SHA-256, the verifier is produced by:
  //   SELECT concat('"', rolname, '" "', rolpassword, '"') FROM pg_authid WHERE rolname = 'username';
  // We emit a placeholder comment; operators populate via the companion SQL:
  //   \copy (SELECT concat('"', rolname, '" "', rolpassword, '"') FROM pg_authid WHERE rolpassword IS NOT NULL) TO /etc/pgbouncer/userlist.txt
  return [
    "# Auto-generated by scripts/pgbouncer/provision-pgbouncer.ts (P499)",
    "# Populate with SCRAM-SHA-256 verifiers from pg_authid:",
    "#   psql -c \"\\copy (SELECT concat('\"', rolname, '\" \"', rolpassword, '\"') FROM pg_authid WHERE rolpassword IS NOT NULL) TO '/etc/pgbouncer/userlist.txt'\"",
    "# Then reload: systemctl reload pgbouncer",
  ].join("\n") + "\n";
}

function writeOrPrint(path: string, content: string, label: string): void {
  if (DRY_RUN) {
    console.log(`\n=== [DRY RUN] ${label} → ${path} ===\n${content}`);
  } else {
    writeFileSync(path, content, { encoding: "utf-8", mode: 0o640 });
    console.log(`Written: ${path}`);
  }
}

async function reloadPgBouncer(): Promise<void> {
  if (DRY_RUN) {
    console.log("[DRY RUN] Would run: systemctl reload pgbouncer");
    return;
  }
  try {
    execSync("systemctl reload pgbouncer", { stdio: "inherit" });
    console.log("PgBouncer reloaded.");
  } catch {
    console.warn(
      "systemctl reload pgbouncer failed — PgBouncer may not be running yet. " +
        "Start it with: systemctl start pgbouncer",
    );
  }
}

async function provision(pool: Pool): Promise<void> {
  const projects = await loadProjects(pool);
  console.log(`Found ${projects.length} active tenant project(s).`);

  writeOrPrint(PGBOUNCER_INI, buildIni(projects), "pgbouncer.ini");

  // Only write userlist if it doesn't already exist (operators manage passwords)
  let userlistExists = false;
  try {
    readFileSync(USERLIST_TXT);
    userlistExists = true;
  } catch {
    // file doesn't exist
  }
  if (!userlistExists) {
    writeOrPrint(USERLIST_TXT, buildUserlist(), "userlist.txt");
  } else {
    console.log(`Skipped: ${USERLIST_TXT} already exists (managed by operator).`);
  }

  await reloadPgBouncer();
}

/**
 * Watch mode: listen for tenant_db_provisioned NOTIFY events on a direct pg.Client
 * and re-provision PgBouncer within the required 60-second SLA (AC-2 in P499).
 * Uses a direct pg.Client (not pool) to avoid PgBouncer transaction-mode incompatibility.
 */
async function watchLoop(pool: Pool): Promise<void> {
  const { Client } = await import("pg");
  const client = new Client({
    host: PGHOST,
    port: PGPORT_DIRECT,
    user: PGUSER,
    database: PGDATABASE,
    keepAlive: true,
  });
  await client.connect();
  await client.query("LISTEN tenant_db_provisioned");
  console.log("Watching for tenant_db_provisioned notifications...");

  client.on("notification", async (msg) => {
    console.log(`NOTIFY tenant_db_provisioned received (payload: ${msg.payload ?? "none"}). Re-provisioning...`);
    try {
      await provision(pool);
    } catch (err) {
      console.error("Re-provision failed:", err);
    }
  });

  client.on("error", (err) => {
    console.error("LISTEN client error:", err);
    process.exit(1); // Let systemd restart us
  });

  // Keep the process alive; the LISTEN client drives the loop
  await new Promise<never>(() => {});
}

async function main(): Promise<void> {
  const pool = new Pool({
    host: PGHOST,
    port: PGPORT_DIRECT,
    user: PGUSER,
    database: PGDATABASE,
    max: 3,
  });

  try {
    await provision(pool);

    if (WATCH_MODE) {
      await watchLoop(pool);
    }
  } finally {
    if (!WATCH_MODE) {
      await pool.end();
    }
  }
}

main().catch((err) => {
  console.error("provision-pgbouncer failed:", err);
  process.exit(1);
});
